run-emulator:
	-kill -9 $(shell lsof -ti :8081); firebase emulators:start --import=./firebase-export-1773394176095qUQO0V --export-on-exit=./firebase-export-1773394176095qUQO0V

run-kill:
	-kill -9 $(shell lsof -ti :8081)

run-emlt:
	firebase emulators:start --import=./firebase-export-1773394176095qUQO0V --export-on-exit=./firebase-export-1773394176095qUQO0V